load("@io_bazel_rules_go//go:def.bzl", "go_library")

go_library(
    name = "go_default_library",
    srcs = ["jpeg.go"],
    importpath = "github.com/thomask-m/masrepo/go/src/mas/compression/jpeg",
    visibility = ["//visibility:public"],
)
